default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: small_time_grocer_development

test:
  <<: *default
  database: small_time_grocer_test

production:
  <<: *default
  database: small_time_grocer_production
  username: small_time_grocer
  password: <%= ENV['SMALL_TIME_GROCER_DATABASE_PASSWORD']
